sudo: required
services:
  - docker

before_install:
  - docker build -t reacttest -f Dockerfile.dev .

script:
  - docker run -e CI=true reacttest npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: ap-south-1
  app: "react-travis"
  env: "ReactTravis-env"
  bucket_name: "elasticbeanstalk-ap-south-1-345800986069"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
